export const PROJECTS = [
  { id: '3d-ai-interviewer',     title: '3D AI Interviewer', cover: '/assets/images/projects/Covers/CrackAI.webp',  year: '2026', category: 'Web Application', tags: ['Llama 3.2 3B','Blender','Three.js'], github: 'https://github.com/Vivek-the-creator/3D-AI-INTERVIEWER', images: ['/assets/images/projects/CyberDiagWebsite/image1.png','/assets/images/projects/CyberDiagWebsite/image2.png','/assets/images/projects/CyberDiagWebsite/image3.png'], desc: 'An advanced, AI-driven recruitment platform designed to automate and enhance the interview process using 3D avatars, real-time response analysis, and multi-model interaction.' },
  { id: 'verve',         title: 'Verve', cover: '/assets/images/projects/Covers/Verve.webp', year: '2025', category: 'Mobile App',          tags: ['Flutter','Firebase'], github: 'https://github.com/Vivek-the-creator/Verve', images: ['/assets/images/projects/Verve/image1.png','/assets/images/projects/Verve/image2.png','/assets/images/projects/Verve/image3.png'], desc: 'Verve 🥗 is an AI-powered nutritional advisor designed to help manage chronic diseases like diabetes and hypertension. It delivers personalized meal plans, tracks progress, and offers condition-specific dietary insights to support healthier living through intelligent, tailored nutrition.' },
  { id: 'aurora-voices', title: 'Aurora Voices', cover: '/assets/images/projects/Covers/AuroraVoices.webp', year: '2026', category: 'Web Application',      tags: ['MongoDB', 'React.js','Express.js','Node.js'], github: 'https://github.com/Vivek-the-creator/AuroraVoices', images: ['/assets/images/projects/auroravoices/image1.png','/assets/images/projects/auroravoices/image2.png','/assets/images/projects/auroravoices/image3.png'], desc: 'A modern, responsive blog application built with React.js and CSS. This application allows users to create, read, edit, and delete blog posts with a beautiful user interface.' },
  { id: 'cardiacare',        title: 'Cardioscope AI', cover: '/assets/images/projects/Covers/Cardiacare.webp', year: '2025', category: 'Web Application',      tags: ['CNN','LSTM','Flask'], github: 'https://github.com/Vivek-the-creator/CardioScope-AI', images: ['/assets/images/projects/Zenith/image1.png','/assets/images/projects/Zenith/image2.png','/assets/images/projects/Zenith/image3.png'], desc: "Cardioscope is an AI-powered ECG analysis platform with a modern web interface, real-time visualization, and multi-format input—providing smart measurements, BPM, and helpful doctor's notes" },
  { id: 'akshara-ai',       title: 'Akshara.AI', cover: '/assets/images/projects/Covers/AksharaAI.webp', year: '2026', category: 'Web Application',      tags: ['JavaScript','Python','MongoDB'], github: 'https://github.com/Vivek-the-creator/Akshara.AI', images: ['/assets/images/projects/skymcdb/image.png','/assets/images/projects/skymcdb/image2.png','/assets/images/projects/skymcdb/image3.png','/assets/images/projects/skymcdb/image4.png'], desc: 'Akshara.AI is an AI-powered learning platform that helps children improve language and communication skills through interactive activities and conversations. It creates a fun and personalized learning experience using speech, writing and storytelling.' },
  { id: 'ultracode-ai',   title: 'Ultracode AI', cover: '/assets/images/projects/Covers/UltracodeAI.webp', year: '2025', category: 'IntelliJ Extension', tags: ['Java','Multi-Model'], github: 'https://github.com/Vivek-the-creator/UltraCodeAI', images: ['/assets/images/projects/chromablock/image1.png','/assets/images/projects/chromablock/image2.png','/assets/images/projects/chromablock/image3.png'], desc: 'UltraCodeAI is an IntelliJ IDEA plugin that embeds an AI coding copilot directly in the IDE with multi-model chat with streaming responses that can work offline.' },
  { id: 'oxocare',      title: 'Oxocare', cover: '/assets/images/projects/Covers/Oxocare.webp', year: '2025', category: 'Mobile App', tags: ['Kotlin','OCR','NLP'], github: 'https://github.com/Vivek-the-creator/OXOCARE', images: ['/assets/images/projects/symphony/image2.png','/assets/images/projects/symphony/image.png','/assets/images/projects/symphony/image3.png'], desc: 'Oxocare is a smart OCR-powered Android app built to assist during medical emergencies and digitize medical documents with high accuracy, maintain records in an global patient database.' },
  { id: 'gazevoice',          title: 'GazeVoice', cover: '/assets/images/projects/Covers/Gazevoice.webp', year: '2025', category: 'Website',        tags: ['WebGazer.js','WebRTC','React.js'], github: 'https://github.com/Vivek-the-creator/GazeVoice',  images: ['/assets/images/projects/gazevoice/image.png'], desc: 'A browser-based assistive communication system that enables ALS patients to communicate using real-time eye gaze tracking via webcam. Designed to be low-cost, accessible, and hardware-free.' },
]

export const SKILLS = [
  { group: 'frontend',   label: 'Frontend',          items: ['HTML','CSS','JavaScript','TypeScript','React','Next.js','Tailwind','Bootstrap','Electron'] },
  { group: 'animation',  label: 'Animation & 3D',    items: ['GSAP','Lenis','Barba.js','Three.js','WebGL','Blender'] },
  { group: 'backend',    label: 'Backend',            items: ['Node.js','Express.js','Python','Java','PHP','Netlify'] },
  { group: 'database',   label: 'Databases',          items: ['MySQL','PostgreSQL','MongoDB','Supabase'] },
  { group: 'devops',     label: 'DevOps & Tools',     items: ['Docker','Vercel','Git','GitHub','GitLab','Cloudflare'] },
  { group: 'sysadmin',   label: 'System & Security',  items: ['Linux','Bash','Shell','Owasp','Metasploit','Nmap','OpenVAS','Ossec'] },
  { group: 'design',     label: 'Design',             items: ['Photoshop','Canva','Figma'] },
]

export const AWARDS = [
  { org: 'GSAP',     site: 'lukebaffait.fr', prize: 'Site of the week', date: '17 06 2026', img: '/assets/images/projects/Covers/Portfolio.avif' },
  { org: 'Awwwards', site: 'lukebaffait.fr', prize: 'Nominee',          date: '26 06 2026', img: '/assets/images/projects/Covers/Portfolio.avif' },
]

export const ARROW_SVG = `<svg style="width:1.25em;height:1.25em;vertical-align:-0.25em;" viewBox="0 0 84 85" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="M11 38H54L37 21H51L73 43L51 65H37L54 48H11Z"/></svg>`
